"""inital imgrations

Revision ID: f290a3f83a5b
Revises: 
Create Date: 2017-12-10 19:06:43.048154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f290a3f83a5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=20), nullable=True),
    sa.Column('txt', sa.String(length=2000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'texts', 'topic')
    op.drop_column(u'texts', 'date')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column(u'users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('password', sa.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.add_column(u'texts', sa.Column('date', sa.VARCHAR(length=20), nullable=True))
    op.add_column(u'texts', sa.Column('topic', sa.VARCHAR(length=20), nullable=True))
    op.drop_table('artis')
    # ### end Alembic commands ###
